# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: 1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef

# Devise configuration
devise:
  secret_key: 1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
